spring:
  application:
    name: '@ext.longName@ - PROD'

management:
  endpoints:
    web:
      exposure:
        include: 'info,health'

secure-aws-config:
  parameters:
    pathBase: /sampleapi/prod
    region: ap-southeast-2
#  secrets:
#    secretName: sampleapi/prod
#    region: ap-southeast-2

